### ISSUE TITLE
Message box for manufacturing not showing error message correctly

### ISSUE THREAD

**Issue by ekg98** [EvEmu-Project/evemu_Crucible#103]
**Describe the bug**
The message box for manufacturing items is not showing the required skill and skill level correctly when you don't have them trained.

**To Reproduce**
1. attempt to manufacture item without required skill level
2. receive message

**Expected behavior**
correct required skill level and skill should show in error box

**Screenshots**
![IMG_8716](https://user-images.githubusercontent.com/24751528/115152382-da8ca900-a03e-11eb-82d5-20d82cac6f91.jpg)

**System Details (please complete the following information):**
 - Server OS: Windows 10
 - Docker
 - EVEmu Version 0.8.3

**Comment by zhyrohaad** [comment]
i dont recall testing that before.
will look into and correct as i get time (unless somebody else beats me to it)

**Comment by jdhirst** [comment]
I have fixed this in 990d5ca and will be released into master in 0.8.4.
![image](https://user-images.githubusercontent.com/9157196/132945566-97bf288f-52a7-429c-ad20-b7cb8fa374a9.png)
