### ISSUE TITLE
PyPackedRows do not support NULL (PyNone) values

### ISSUE THREAD

**Issue by Almamu** [EvEmu-Project/evemu_Crucible#104]
**Describe the bug**
The current EVEMarshal implementation on EVEmu does not support PyNone values for PyPackedRows, which breaks different things like SOV, which is being worked on staging.

**Additional context**
This feature has not been supported for 10 years, It's gotten to the point that supporting it will bring down parts of the server that already work. So further development will be needed once the feature is ready, so everything comes back to normal.

**Comment by Almamu** [comment]
The support for this feature should be finalized in this commit: 883f14e3d430505966f35d3de78794a2f004c8fb
Please use the branch now to fix any regressions that this patchset might bring into the server, preliminary tests show that the damage might be minimal, but I that won't be really known until we test everything that uses PyPackedRows

**Comment by jdhirst** [comment]
So far everything looks good, I have merged it into staging to allow development to continue with new features. If any issues occur, we can merge fixes in.

**Comment by Almamu** [comment]
Looks like development is going just fine, I'd say that we can close this issue and open specific bug reports if anything is found.

**Comment by Almamu** [comment]
Fixed on 883f14e3d430505966f35d3de78794a2f004c8fb, d7b7e3c7b7cad754f9968b416d5e403f351e79ab, 8734cef519797fb42ee83d573bc90348621799d6, f1477d5c4fbacc8e861e691f96e90500266a168e, f1477d5c4fbacc8e861e691f96e90500266a168e and merged in b7d5032325284e9bb4ba3a66006a9c2e01694d55
