### ISSUE TITLE
[Future] Properly implement UserError argument formatting

### ISSUE THREAD

**Issue by Almamu** [EvEmu-Project/evemu_Crucible#108]
**Is your feature request related to a problem? Please describe.**
Right now EVEmu throws UserErrors in a weird way that makes it harder to know what exactly is being done at a quick glance. On top of that, the implementation is missing on all the formating options the client has (like using translated messages, formating time, date, etc on the specific locale). A nice way to start improving the EVEmu source code, without making drastic changes to it would be starting with this kind of classes that are used everywhere, not really clear to most and hard to understand. So with this issue I aim to start improving this kind of things.

**Describe the solution you'd like**
Implement better support for UserErrors and make them simpler to use, maybe adding some methods to it and hidding the "raw" object manipulation would be a good start.

**Additional context**
fmtMapping is the key of what we can do ;)

This is the first area I thought could be improved without drastic changes, if there's any other place that could get some love that's more important than this one, under the same conditions, please let me know. It'd be ideal to improve the core over time and get rid of some of the code-smells the project has. We can comment this issue on discord if anyone has questions or suggestions

**Comment by Almamu** [comment]
I've uploaded a draft of what I meant with the changes. I feel like a fluent API for the UserError makes it easier to use. Any feedback would be appreciated on what you think ;)

It would be a good idea to get CustomError on the same boat too. Although creating classes for every exception in the game would be a bit too much, some middle ground, like creating one for the most used ones, would be best.

This is the full commit with the changes: 7bf9f78a770653056e042e5f053a349b24ccf04d

**Comment by jdhirst** [comment]
@Almamu I have merged this into staging; it looks a great re-implementation of handling UserErrors!

While testing in staging, I ran into an issue with CustomErrors, will that have changed much? 

Check this out:
```
09:33:39 [CorpCall] CorpRegistryBound::Handle_CreateAlliance() size=4
09:33:39 [CorpCallDump]   Call Arguments:
09:33:39 [CorpCallDump]      Tuple: 4 elements
09:33:39 [CorpCallDump]       [ 0]    WString: 'Testing Alliance'
09:33:39 [CorpCallDump]       [ 1]    WString: 'TSTA'
09:33:39 [CorpCallDump]       [ 2]    WString: 'This is the testing alliance...'
09:33:39 [CorpCallDump]       [ 3]     String: ''
09:33:39 [CorpCallDump]  Named Arguments:
09:33:39 [CorpCallDump]   machoVersion
09:33:39 [CorpCallDump]        Integer: 1
09:33:39 [CorpTrace]  Call_CreateAlliance
09:33:39 [CorpTrace]  allianceName='Testing Alliance'
09:33:39 [CorpTrace]  shortName='TSTA'
09:33:39 [CorpTrace]  description='This is the testing alliance...'
09:33:39 [CorpTrace]  url=''
09:33:39 [SvcError] Anna: Cannot afford alliance startup costs!

Thread 1 "eve-server" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b5c605 in __strlen_avx2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7b5c605 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff7a684f8 in __vfprintf_internal () from /lib64/libc.so.6
#2  0x00007ffff7a79015 in __vasprintf_internal () from /lib64/libc.so.6
#3  0x000000000110d6b4 in MakeCustomError (fmt=0x1189f50 "You must have %s ISK to create an alliance.")
    at /home/fedora/server/src/eve-common/utils/EVEUtils.cpp:48
#4  0x0000000000c1d300 in CorpRegistryBound::Handle_CreateAlliance (this=0xa3c53c0, call=...)
    at /home/fedora/server/src/eve-server/corporation/CorpRegistryBound.cpp:2489
#5  0x0000000000c21145 in PyCallableDispatcher<CorpRegistryBound>::Dispatch (this=0xa3c5420, 
    method_name="CreateAlliance", call=...) at /home/fedora/server/src/eve-server/PyServiceCD.h:68
#6  0x0000000000a92ed9 in PyCallable::Call (this=0xa3c53c0, method="CreateAlliance", args=...)
    at /home/fedora/server/src/eve-server/PyCallable.cpp:42
#7  0x0000000000a91881 in PyBoundObject::Call (this=0xa3c53c0, method="CreateAlliance", args=...)
    at /home/fedora/server/src/eve-server/PyBoundObject.cpp:46
#8  0x0000000000a57e75 in Client::Handle_CallReq (this=0x2306ec0, packet=0xa3fe120, req=...)
    at /home/fedora/server/src/eve-server/Client.cpp:2560
#9  0x0000000000f93415 in EVEPacketDispatcher::DispatchPacket (this=0x2306ee0, packet=0xa3fe120)
    at /home/fedora/server/src/eve-common/network/EVEPktDispatch.cpp:82
#10 0x0000000000a4a876 in Client::ProcessNet (this=0x2306ec0)
    at /home/fedora/server/src/eve-server/Client.cpp:300
#11 0x0000000000a70ca7 in EntityList::Process (this=0x1591bf0)
    at /home/fedora/server/src/eve-server/EntityList.cpp:192
#12 0x0000000000a3608f in main (argc=1, argv=0x7fffffffe3a8)
    at /home/fedora/server/src/eve-server/eve-server.cpp:900
```
This is the call being made from CorpRegistryBound:
```
        throw PyException(MakeCustomError("You must have %s ISK to create an alliance.", ally_cost));
        return nullptr;
```

**Comment by zhyrohaad** [comment]
not sure if this was fixed, but the custom error listed above should be passing a numeric value, (%i, %d, %u, or %f) and not a string (%s)

**Comment by Almamu** [comment]
Yes, we solved that through discord. The changes seem to work fine and they're in staging for quite some time already, so I guess we can close the issue soon.

**Comment by jdhirst** [comment]
Yeah everything has been good so far; we should proceed to close this off.
