### ISSUE TITLE
Planet Management table "piPins" missing column

### ISSUE THREAD

**Issue by DeerHunt3r** [EvEmu-Project/evemu_Crucible#113]
**Describe the bug**
While testing the planet management / colony management this error was found in the logs

server_1  | 14:41:56 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:345): DBCore Query - #1054 in 'UPDATE piPins SET  programType = 2307,  headRadius = 0.010000,  qtyPerCycle = 998,  schematicID = 2448,  expiryTime = 132651349166104832,  cycleTime = 8999999488,  installTime = 132651313166103040,  lastRunTime = 132651313166103056 WHERE pinID = 140001386': Unknown column 'qtyPerCycle' in 'field list'

the column is missing from my DB,  

**To Reproduce**
1. open planet management
2. start putting in the colony stuff
3. notice the pins are unmanageable

**Expected behavior**
Not exactly sure,  but I assume the pins would be manageable routes and other stuff would be configurable too

**Screenshots**

**System Details (please complete the following information):**
 - Server OS: Ubuntu 20.04 Server
 - Docker 
 - EVEmu Version commit 

**Additional context**
:56 [PlanetTrace] PlanetMgr::UserUpdateNetwork() - loop: 0, command: AddExtractorHead(10)
server_1  | 14:41:56 [PlanetTrace] PlanetMgr::UserUpdateNetwork() - loop: 1, command: MoveExtractorHead(12)
server_1  | 14:41:56 [PlanetTrace] PlanetMgr::UserUpdateNetwork() - loop: 2, command: InstallProgram(13)
server_1  | 14:41:56 [PlanetTrace] PlanetMgr::GetProgramResultInfo() - cycleTime:0.25, iCycleTime:8999999488, length:1.00, numCycles:4, qtyPerCycle:998, heads: 1, headRadius:0.0100
server_1  | 14:41:56 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:345): DBCore Query - #1054 in 'UPDATE piPins SET  programType = 2307,  headRadius = 0.010000,  qtyPerCycle = 998,  schematicID = 2448,  expiryTime = 132651349166104832,  cycleTime = 8999999488,  installTime = 132651313166103040,  lastRunTime = 132651313166103056 WHERE pinID = 140001386': Unknown column 'qtyPerCycle' in 'field list'
server_1  | 14:41:56 [DB Error] UpdateECUPin - Unable to update pin: Unknown column 'qtyPerCycle' in 'field list'
server_1  | 14:41:56 [PlanetTrace] PlanetMgr::UserUpdateNetwork() - loop: 3, command: CreateLink(3)
server_1  | 14:41:56 [ItemWarning] II::Spawn creating generic item for type 2280, cat 41.
server_1  | 14:41:56 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:320): DBCore - Status != Connected
server_1  | 14:41:56 [DB Msg] DBCore error detected.  Look for error msgs in logs prior to this point.

**Comment by jdhirst** [comment]
@DeerHunt3r Can you please create a new migration using EVEDBTool and create a pull request with that change?

**Comment by D33rhunt3r** [comment]
working on it,  I got the migration created on my dev ubuntu box and I'm trying to push the change but getting access denied.  Please advise

**Comment by jdhirst** [comment]
@D33rhunt3r you need to do this to a fork, and then create a PR from that.

**Comment by DeerHunt3r** [comment]
Done,  Please review

**Comment by jdhirst** [comment]
PR has been merged. Thanks! Closing issue
