### ISSUE TITLE
EVE legal

### ISSUE THREAD

**Issue by Metalica** [EvEmu-Project/evemu_Crucible#119]
For github main web page. So that it is more protected.

"EVE Online and the EVE logo are the registered trademarks of CCP hf. All rights are reserved worldwide. All other trademarks are the property of their respective owners. EVE Online, the EVE logo, EVE and all associated logos and designs are the intellectual property of CCP hf. All artwork, screenshots, characters, vehicles, storylines, world facts or other recognizable features of the intellectual property relating to these trademarks are likewise the intellectual property of CCP hf."

**Comment by jdhirst** [comment]
We already have a legal disclaimer on the project page regarding what we support the use of this code for. (namely, we don't support it, and it is explicitly not supported for the running of public servers)

This could be added to the Wiki if you'd like but as for the code itself, we avoid using the trademarks as it is only a server emulator and we do not provide access to client files.
