### ISSUE TITLE
Adding last game client 1.22 Citadel

### ISSUE THREAD

**Issue by Metalica** [EvEmu-Project/evemu_Crucible#121]
Adding support for Citadel before alpha and omega clones.

Release date: 27 April 2016

"Citadel introduced Upwell structures (new player owned stations referred to as citadels[46]), Force Auxiliaries (a new line of logistics themed capital ships), a rebalance of existing capital ships, new super-weapons for citadels and Titans, a unique citadel named the 'Palatine Keepstar', of which only one may exist in the game at any given time, and 'Recurring Opportunities' (a daily quest for bonus skill points feature, which have since been removed.).[47]

Citadel was the first major expansion to Eve Online since CCP made changes to their release cadence"

**Comment by VizanArkonin** [comment]
Given the amount of changes it will trigger, moving to a newer client version is unlikely now. 
It's not enough to just change a couple packets here and there, as our past experience shown already. 
If someone would take it, then it might be a good candidate for separate branch, but until then - we need to make current code somewhat functional first.

**Comment by jdhirst** [comment]
As VizanArkonin stated, we have no plans currently to move to a different client base as this would require massive code change. Feel free to fork EVEmu and create your own branch, however EVEmu master will stay on Crucible for the forseeable future.
