### ISSUE TITLE
Manufacturing job can't be installed - completedStatusID row has no default value and is not inserted

### ISSUE THREAD

**Issue by VizanArkonin** [EvEmu-Project/evemu_Crucible#127]
**Description**
Installing an industry job will result in a DB error:

```
08:27:39 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:345): DBCore Query - #1364 in 'INSERT INTO ramJobs (ownerID, installerID, assemblyLineID, installedItemID, installTime, beginProductionTime, endProductionTime, runs, outputFlag, licensedProductionRuns) VALUES (90000000, 90000000, 88751, 140000051, 132715024592487808, 132715024592487680, 132715027462487680, 1, 4, 0)': Field 'completedStatusID' doesn't have a default value

08:27:39 [DB Error] Failed to insert new job to database: Field 'completedStatusID' doesn't have a default value.

08:27:39 [ManufError] Could not InstallJob for Malcolm McCann using Antimatter Charge S Blueprint

08:27:41 [Service] ramProxy::GetJobs2()

08:27:41 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:320): DBCore - Status != Connected
```

Materials get consumed, but job is not installed and BP is gone

**Steps To Reproduce**
Any blueprint will do. I'll describe my scenario
1. Gather materials and get an Antimatter Charge S blueprint
2. Proceed to installing the job
3. Confirm installation

**Expected behavior**
Job gets installed and gets displayed in Science and Industry window

**System Details:**
 - Server OS: Windows 10
 - Docker build
 - EVEmu Version 0.8.3, staging branch

**Comment by VizanArkonin** [comment]
From the look of it - we do not allow completedStatusID column to be null, yet we do not provide it in insert statement.
I think we can either provide a default value for the column, or complete insert statement.

Which raises the question - how does client\server use this value? will it be ok to just hard-code it to, say, 1?

**Comment by zhyrohaad** [comment]
this value shoes in job status client as either {in progress/completed}.
i dont remember the number offhand, but it should be noted in code.
once the job is installed, it *should* set statusID as "in progress" or whatever the wording is.

as a side note, there will be more of these "no default" errors,
on my testing/dev branch, ,my db had most defaults set, so i didnt specify in the db insert command.
these will have to be either updated in db for a default value, or set in code.
with the way the db is being updated now,, it would be much easier to update the insert command in code to specify all values for adding columns to tables.

cheers

**Comment by katz1** [comment]
1. I tried initializing the `completedStatusID` with just 0, and it seemed to be working fine. The job was `In progress` on the UI and switched to `Ready` afterwards.

2. The query also misses `installedInSolarSystemID`, I initialized this with `args.lineLocationID`, which I hope is a station.

3. During delivery a different query had issues in `FactoryDB::GetJobProperties`. It tried retrieving `job.eventID` which is not a column, and I have no idea what it is supposed to be, I don't see any similar field around R&M. I just filled the return data with `0`, delivery seems to be working fine like this.

I made a PR in case you want to take this.

**Comment by jdhirst** [comment]
@katz1 I believe eventID is a calendar event ID, which would be created for when the manufacturing job is initialized. I suggest upon the installation of a new manufacturing job, we create a new calendar event when the job is started. Therefore we can return this ID later on.

**Comment by zhyrohaad** [comment]
> 1. I tried initializing the `completedStatusID` with just 0, and it seemed to be working fine. 

that was what it needed.   once complete, it will (should) update itself.

> 2. The query also misses `installedInSolarSystemID`, I initialized this with `args.lineLocationID`, which I hope is a solar system.

it is not.  `args.lineLocationID` is station/array id.
systemID is in the data available to that method, but i dont remember offhand what map holds it.
another option which is fairly cheap, is to pull systemID from stationID.  (we dont have arrays working yet)
something along the lines of the following PARTIAL/PSEUDO code....
`if (isStation(args.lineLocationID)
    sysID = sDataMgr.GetSystemID(args.lineLocationID); `
--- search code for `sDataMgr.GetSystemID` for examples of working code.

> 3. During delivery a different query had issues in `FactoryDB::GetJobProperties`. It tried retrieving `job.eventID` which is not a column, and I have no idea what it is supposed to be, I don't see any similar field around R&M. I just filled the return data with `0`, delivery seems to be working fine like this.
>@katz1 I believe eventID is a calendar event ID, which would be created for when the manufacturing job is initialized. I suggest upon the installation of a new manufacturing job, we create a new calendar event when the job is started. Therefore we can return this ID later on.

i kinda think so as well, but all the calendar events for RAM were working.  
will need a bit of looking over to verify and fix as needed.

thanks

**Comment by zhyrohaad** [comment]
what is `installedInSolarSystemID` used for?
i dont see a reference to this in client

**Comment by jdhirst** [comment]
Good question, I have no idea, I just got it from this issue. I'll have a look tomorrow and see whether it even needs to be there.

**Comment by VizanArkonin** [comment]
Fix seems to be working - successfully installed and finished an industry job.
There are some more funky stuff with S&I, but that's a story for another ticket :)
