### ISSUE TITLE
Delivering Industry job also grants items, required for Invention.

### ISSUE THREAD

**Issue by VizanArkonin** [EvEmu-Project/evemu_Crucible#141]
**Description**
Upon delivering the Industry job, you get the following:
- Produced items (expected)
- Materials, required for invention job (very much not expected)
- Skillbook, required to inject the skill for producing that type of item (also not expected)

So far i only tested it with single BP in scope of assembly line fix, so probably it'll yield even more stuff for other blueprints.

**Steps to reproduce the behavior:**
1. Get\create a blueprint for **Antimatter Charge S**, get\create materials required to produce it.
2. Install a manufacturing job with this BP, 1 run.
3. Wait until finished and press **Deliver**.

**Expected behavior**
Player receives **100 units of Antimatter Charge S**

**Actual behavior**
Player receives **100 units of Antimatter Charge S, 1 Industry skillbook, 1 Incognito Data Interface, 1 Plasma and 1 Electromagnetic Physics datacores.**

**System Details:**
 - Server OS: Windows 10
 - Docker build (remote development sandbox container)
 - EVEmu Version - Staging, e7feda9

Server log is attached - ITEM and MANUF logging sections were fully enabled.
[eve-server.log](https://github.com/EvEmu-Project/evemu_Crucible/files/7295883/eve-server.log)

**Comment by Almamu** [comment]
That's weird, skillbooks shouldn't be created back as there's already a check for that. And datacores belong to a different activity, so that shouldn't happen either. What blueprint did you try so I can reproduce the issue?
