### ISSUE TITLE
Manufacturing material quantities are incorrect

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#142]
When looking into #141, I wanted to check to see what the cause of the invalid number of Nocxium message was, and it brought me into this rabbit hole.

I'm adding this to 0.8.4 since it seems like it'll be a relatively quick/easy fix (I think). I might adjust later if it turns out to not be the case.

So the first thing I checked out was the +1 issue, where Nocxium was requiring 2 units instead of one. Turns out that this is caused by a floating point error:

![image](https://user-images.githubusercontent.com/9157196/136344757-e8a9c749-b17e-4cfb-84c6-b2b294b67a97.png)

We calculate the needed quantity like this:
```
uint32 qtyNeeded = ceil(cur.quantity * rsp.materialMultiplier * runs);
```

Doing the maths here:
```
Tritanium: 184 * 1.1000000014901161 * 1 = 202.40000027418137 (rounded by ceil(), 203)
Pyerite: 15 * 1.1000000014901161 * 1 = 16.500000022351742 (rounded by ceil(), 17)
Nocxium: 1 * 1.1000000014901161 * 1 = 1.1000000014901161 (rounded by ceil(), 2)
```
This explains the Nocxium issue, but doesn't explain why the values are so wrong in general. They don't match up at all with what the game shows. 
To manufacture 1 run of this blueprint, I need the following: (with Level 1 Industry)
248 Tritanium
20 Pyerite
1 Nocxium

We also have settings in the config file which alter material multipliers, and these are shown here:
```
        <MatMod>1.0</MatMod>
        <ProdMod>1.0</ProdMod>
```

To calculate the multipler we do this:
```
            FactoryDB::GetMultipliers(args.AssemblyLineID, pType, into);
            into.materialMultiplier += bpRef->GetME();
            into.materialMultiplier *= sConfig.ram.MatMod;
```
So after the GetME() function returns its response and this gets added to the multipler, we get the value of `1.1000000014901161` which was seen above.

However, what I want to know is where the client gets its' values from that is shows in the blueprint info window. If these are coming from the server, there must be some conflict going on.

So I manually fudged the material multiplier, and it doesn't affect the client, so therefore we know that the client calculates these things independently and our calculations are off. 

I assume Skill level comes into manufacturing, however this doesn't seem to be taken into account. Does anyone know what the formula would be for that?

**Comment by zhyrohaad** [comment]
there was something else going on here, and i had to use floats.
i dont remember what it was, and not sure if i noted in code or not.
there was a reason i did it that way, and now i cant remember what/why

**Comment by jdhirst** [comment]
I've tested this and it appears to be working correctly. Closing for now. Please re-open if issue persists after release.
