### ISSUE TITLE
undocking puts ship in wrong location 

### ISSUE THREAD

**Issue by zhyrohaad** [EvEmu-Project/evemu_Crucible#149]
undocking does not position ship properly to the station dock.

**Comment by jdhirst** [comment]
Yep, noticed this started happening recently, and it seems to be related to ship's mass since differently massed ships undock at different locations, but for same-massed ships, they undock at the same location as each other.

**Comment by jdhirst** [comment]
I think I found it, it only happens when using `.tr` to enter stations, so I guess position is never updated to the station position, so that explains why you undock where you last were in the system.

**Comment by zhyrohaad** [comment]
this should be fixed
need another to verify, pls.

**Comment by zhyrohaad** [comment]
is not fixed.
working on it now.

**Comment by zhyrohaad** [comment]
found and fixed.
