### ISSUE TITLE
Inventory contains a lot of "IsValidLocation" macros, verify if this is needed as-is or should be validItem

### ISSUE THREAD

**Issue by Almamu** [EvEmu-Project/evemu_Crucible#162]
As the issue title says, there's been changes recently to the IsValidLocation macro that need to be validated as it's used through the whole Inventory system which might have been misused.

**Comment by Almamu** [comment]
Expanding on this, what should constitute valid locations? Right now it's just a check for valid solar system, station or solar system, but are "virtual" locations valid too? like 2003 (RAM). @zhyrohaad

**Comment by zhyrohaad** [comment]
as this is relevant to the macro checks, i will mention it here also.
the "IsValidLocationID" macro only checks the itemID is within a set range, and does not verify there is an actual item for the given itemID.  
while this has been 'good enough' before for all checks, i think we are outgrowing its limitations and need to verify some things are actual items.  that is the intention of my update, and current progress.
there are some things in the codebase that really should be verifying the actual "given" itemID exists, while others are ok with verifying the itemID is in the proper range.
virtual locations should also be verified, but i have not looked into that part as of yet.

**Comment by zhyrohaad** [comment]
fixed in https://github.com/EvEmu-Project/evemu_Crucible/commit/d1d09abfd78c41e6e5284cf83e7a3e0d8563b862

**Comment by zhyrohaad** [comment]
> That was actually me fixing an issue with blueprints not moving when doing manufacturing XD Should we approach it like this on the item moving checks or should that be in the macro itself? I'm pretty sure there's other places where that locationID might be useful

oh, thats why i didnt remember it. lol
in that case it is exactly what's needed and where it should be.
i dont think the virtual locations like that should be in the macro...there only used for specific things, so explicit checks are just what we want.

**Comment by zhyrohaad** [comment]
macro naming is updated and complete.  other tests have been reviewed.
the tests for uid range use the macro, where things that need to validate an actual item exists use the new code.

we may need to revisit at a later date when more systems have been updated or mature.
