### ISSUE TITLE
Launching Control Tower on Moon 1 causes tower to vanish

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#163]
For some reason, when launching a tower on Moon 1 of a particular system, it always causes the tower to simply vanish when it is launched. It is in the DB, but it must be at a location far away from the player. 

Will check into this more when I get a chance.

**Comment by zhyrohaad** [comment]
i cant duplicate this.
anchor does funny things at times, but launch works without error

**Comment by jdhirst** [comment]
I haven't been able to reproduce this either recently, closing for now. Please re-open if still an issue after 0.8.5 release to master.
