### ISSUE TITLE
Cannot Train new injected skills on the staging branch

### ISSUE THREAD

**Issue by DeerHunt3r** [EvEmu-Project/evemu_Crucible#167]
**Describe the bug**
This is on the Staging branch.  Skill training errors out when you try to update the skill queue.  with a "STOP: Skill not found" error.  when you log out and log back in the skill is no longer in your skills list.

**To Reproduce**
1. purchase a skill - energy upgrades for example.
![EvemuError](https://user-images.githubusercontent.com/80292862/138499299-b4ce37de-3ef0-49db-ba55-9d2bf649406e.JPG)

2. inject said skill
3. add to skill queue
4. save queue and see error

**Expected behavior**
it should just start training the skill

**Screenshots**

**System Details (please complete the following information):**
 - Server OS: [e.g. Ubuntu 20.04 Server]
 - Docker or direct build
 - EVEmu Version [e.g. 0.8.2 or commit xxxxxxx]

**Additional context**
I've totally rebuilt the server just incase I screwed it up.  but no dice.

**Comment by zhyrohaad** [comment]
found and fixed.
