### ISSUE TITLE
Client crash on WSL(Windows 10 2004, WSL1, Ubuntu)

### ISSUE THREAD

**Issue by NukedBart** [EvEmu-Project/evemu_Crucible#171]
**Describe the bug**
No out pus being given from the console, When getting in the game(select a character and join the game) the client crashes
the server is still running with no outpus

**To Reproduce**
Build the server from current staging branch
Install the db using the dbtool
Run the server
Connect to the server
Login to the game
Select a character and join the game
Crash

**System Details:**
 - Server OS: Windows 10 2004 with WSL1 Distro: Ubuntu
 - Direct build
 - EVEmu Version staging 2021.11.21

**Comment by jdhirst** [comment]
WSL1 does not fully or properly implement Linux system calls. Try it on a VM or with WSL2 and see if it works.

**Comment by NukedBart** [comment]
> WSL1 does not fully or properly implement Linux system calls. Try it on a VM or with WSL2 and see if it works.

it worked previously on wsl1 with the october staging build

**Comment by jdhirst** [comment]
I have tested the latest build in docker on a completely fresh system and it works without issue so there must be some issue specific to your environment.

**Comment by NukedBart** [comment]
Uh, It was because I was running multiple copies of eve-server without noticing it, after terminating the wsl distro and restart it the problem was solved

**Comment by jdhirst** [comment]
Excellent, glad everything is now working for you. Closing confirmed.
