### ISSUE TITLE
compiled.code decrypt

### ISSUE THREAD

**Issue by SantjagoCorkez** [EvEmu-Project/evemu_Crucible#172]
I'd like to mess a bit with some of unimplemented s2c packets, though it's way unclear what does the client expect for a server response. For example: `IndexManager::Handle_GetDevelopmentIndicesForSystem`. I've tried to build a PyDict though the client expects values for `militaryPoints` and `industrialPoints` to be not an integer but rather some kind of an object instance having `points` property existent and set. Passing out a `PyObject` of type `object` does not do: the client strictly prohibits this object type and reports back to the server something about `a hacker attack detected`.

To dig deeper into the client-side python I need to decompile the contents of `compiled.code` though despite the structure of the file is way easy to understand, the contents of each file inside is crypt'd and I've found no way (yet) to restore it back.

Is there a decrypt hint for the files inside `compiled.code` ?

**Comment by Almamu** [comment]
Sounds like keyval is a good candidate for the objects that need to have the ```points``` member. We don't support modifying or decompiling the client officially due to legal issues, so you'll need to figure it out yourself there.
