### ISSUE TITLE
cannot use tractor beam on newly created jetcan.

### ISSUE THREAD

**Issue by idolord** [EvEmu-Project/evemu_Crucible#195]
**Describe the bug**
trying to tractor beam ore jetcan give a "target is anchored" message and don't alow the jetcan to be tracted

**To Reproduce**
1. Go anywhere with one account that is in a fleet with another
2. jettison something with it 
3. make another account with a tractor beam join the location and target the jetcan, thane activate tractor beam
4. See error message

**Expected behavior**
jetcan shoulnt be anchored by default and beeing able to be tracted by tractor beam.

![image](https://user-images.githubusercontent.com/972844/159338776-93f99007-4bf2-4224-9ee0-5c442bf390e4.png)

**Comment by jdhirst** [comment]
Since this is a standard jetcan, there shouldn't be any anchoring at all. Is the original user who dropped the jetcan able to use a tractor beam on it?

**Comment by VizanArkonin** [comment]
As long as player have ownership over jetcan/wreck (white), or they are abandoned (i.e. turned blue), it is possible to tractor those.  The only ones you can't tractor are those that doesn't belong to you (yellow)

**Comment by idolord** [comment]
I will try it tonight but pilot in fleet should have acces to fleet jetcans and jetcans shouldn't ne anchored by défaut even secure vault need to ne anchored ans dont start as anchored. I'll get back to you when the test for owned jetcans IS donne.

**Comment by idolord** [comment]
fixed with https://github.com/EvEmu-Project/evemu_Crucible/pull/198

**Comment by jdhirst** [comment]
Closing as fixed
