### ISSUE TITLE
jetcan not exploding when emptyed

### ISSUE THREAD

**Issue by idolord** [EvEmu-Project/evemu_Crucible#196]
**Describe the bug**
jetcan stay in space enven when the content is emptyed

**To Reproduce**
1. Go to anywhere
2. jettison an item
3. grabb it in your cargohold
4. See je jettison happily saying even if empty

**Expected behavior**
jetcan should self destruct if emptied.

**Screenshots**
![image](https://user-images.githubusercontent.com/972844/159339387-8eb41d22-f1f6-49f7-8525-3c93ce409e3d.png)

**Comment by jdhirst** [comment]
That should be a simple check which can be added to the ContainerSE class. It can automatically destroy itself if it sees no cargo inside itself. I can't think of a better place to add it; @Almamu your thoughts?

It would be important that this check ONLY apply to Jetcans, not other containers, so a typeID check would need to be in place as well.

**Comment by idolord** [comment]
fixed with https://github.com/EvEmu-Project/evemu_Crucible/pull/198

**Comment by jdhirst** [comment]
Closing as fixed
