### ISSUE TITLE
Locate character button causes segfault

### ISSUE THREAD

**Issue by ekg98** [EvEmu-Project/evemu_Crucible#2]
**Describe the bug**
Locate Character button causes segfault when depressed in the agent conversation dialog box.

**To Reproduce**
1) open agent conversation dialog with Dakiribi Yamaden in Mehatoor system
2) depress locate character button

**Expected behavior**
Unsure expected behavior of the button but should not cause segfault when executed

**System Details (please complete the following information):**
 - Server OS: Windows 10
 - Docker
 - EVEmu Version 0.8.2

**Comment by zhyrohaad** [comment]
this is new also.
current fix.....
dont push the Locate Character button.  ;)

**Comment by jdhirst** [comment]
This is fixed. Issue was related to DB column type.
