### ISSUE TITLE
crash on login at ubuntu 18.04

### ISSUE THREAD

**Issue by NukedBart** [EvEmu-Project/evemu_Crucible#210]
**Describe the bug**
It crashes

**To Reproduce**
1. Build
2. DB Install(probably not fully migrated, SQL syntax error for some sqls)
3. Login
4. Crash

**Expected behavior**
Gameplay

**System Details: **
 - Server OS: Ubuntu 18.04 Server
 - Docker or direct build
 - EVEmu Version 4/Apr 2022 latest

**Additional context**
```22:36:28 [DB Error] DoQuery_locked(/evemubuild/evemu_Crucible/src/eve-core/database/dbcore.cpp:345): DBCore Query - #1146 in ' SELECT expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID FROM dgmExpressions LIMIT 9000, 18000': Table 'evemu.dgmExpressions' doesn't exist
22:36:28 [DB Error] GetExpressions(/evemubuild/evemu_Crucible/src/eve-server/cache/BulkDB.cpp:319): Error in GetExpressions: Table 'evemu.dgmExpressions' doesn't exist
22:36:28 [DB Error] DoQuery_locked(/evemubuild/evemu_Crucible/src/eve-core/database/dbcore.cpp:320): DBCore - Status != Connected
22:36:28 [DB Error] DoQuery_locked(/evemubuild/evemu_Crucible/src/eve-core/database/dbcore.cpp:345): DBCore Query - #1146 in ' SELECT expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID FROM dgmExpressions': Table 'evemu.dgmExpressions' doesn't exist
22:36:28 [DB Error] GetExpressions(/evemubuild/evemu_Crucible/src/eve-server/cache/BulkDB.cpp:319): Error in GetExpressions: Table 'evemu.dgmExpressions' doesn't exist
22:36:28 [DB Error] DoQuery_locked(/evemubuild/evemu_Crucible/src/eve-core/database/dbcore.cpp:320): DBCore - Status != Connected
22:36:30 [Service] bulkMgr::GetFullFilesChunk()```

**Comment by jdhirst** [comment]
@NukedBart We don't really support MySQL, only MariaDB. Your experience may vary with MySQL. I suggest trying it in Docker or using MariaDB 10.4 or later.

**Comment by jdhirst** [comment]
Also, if your DB is not fully migrated, I suggest running `./evedbtool up` to finish migration. If you are on staging, it may fail as staging has had changes in the db structure which aren't yet finalized.

In that case, you may want to nuke the db and reinstall it.

However, there should be no such changes in the master db. That one should work fine without migration failures.

**Comment by NukedBart** [comment]
using mysql caused the issue, do not use mysql

**Comment by jdhirst** [comment]
Thanks for the confirmation! I have updated the wiki to reflect this more clearly in the new users guide:
https://wiki.evemu.dev/index.php?title=New_Users_Guide&diff=2942&oldid=2132
