### ISSUE TITLE
The brokers fee in the market is strange

### ISSUE THREAD

**Issue by fumikejin** [EvEmu-Project/evemu_Crucible#214]
When I sell goods in the market, for example, total 15isk. 
The brokers fee was 10000%, which cost me 1500isk.
Whether I sell anything in the market, the brokers fee always is 10000%.
I have tried many times and still have this bug.

**Screenshots**
When I sell it：
![image](https://user-images.githubusercontent.com/101409988/162474654-ffda38ee-f046-4e67-bb72-8fcebd522a2d.png)
Brokers fee：
![image](https://user-images.githubusercontent.com/101409988/162474871-7bea9e3a-312d-4952-a3e9-5190abcc600f.png)

**Comment by jdhirst** [comment]
@fumikejin I guess its good to be the broker 😁 

On a serious note, yeah its a bug, I thought we had this resolved. Which version are you running?

**Comment by fumikejin** [comment]
My EVE Online Client is 360229.
 2 weeks ago,I followed the Guide（on https://wiki.evemu.dev/wiki/New_Users_Guide）to Set up my system for EVEmu . I think I'm running the EVEmu latest version.

**Comment by fumikejin** [comment]
I try to be a 'normal' player,the brokers fee be normal.
