### ISSUE TITLE
Adding server config to connect to Jovian empire and UUA-F4

### ISSUE THREAD

**Issue by Metalica** [EvEmu-Project/evemu_Crucible#223]
**Is your feature request related to a problem? Please describe.**
 - Adding server config to enable gate link to Jovian empire and UUA-F4 with rest of the eve map.

**Additional context**
 - Labels: Future.

**Comment by bnaambo** [comment]
well u could jump via commands to jovian systems however there is nothing really interesting the stations there are mostly gallente design

**Comment by jdhirst** [comment]
This is out of scope for the project as we try to implement the game according to its original design. If you want to travel there, you can use a command the same way a GM would.
