### ISSUE TITLE
Broken UI Elements

### ISSUE THREAD

**Issue by kimrosebush** [EvEmu-Project/evemu_Crucible#247]
Description:
With the recent build, I am unable to pull up certain UI elements.
- Right clicking in space
- Right clicking player in chat
- Broken chat UI

Debug error:
```
20:24:51 [Service] config::GetDynamicCelestials() - when right clicking in space.
20:24:52 [Service] corpBookmarkMgr::GetBookmarks() - when right clicking player in chat
```

Reproduction:
1. Build server.
2. Login to the server.
3. Attempt to use the said interfaces.
4. See error.

Expected behaviour:
- Normal operation of the UI

Screenshots:

Broken chat:
![image](https://user-images.githubusercontent.com/74399393/213885975-02b18a56-2dc2-40c5-b9cf-9f0a4fa65c7d.png)

System Details:
 - Server OS: Debian 11 x64, ESXi VM
 - Docker
 - EVEmu db81c4097bfc319fabbca70a74bbf070cf3917b0

Additional Context:
- I am able to bring up the context menu of my active ship.

**Comment by jdhirst** [comment]
@Almamu I wonder if this is related to service rewrite? I haven't been able to reproduce it though... chat is working just fine on my test docker builds

**Comment by Almamu** [comment]
There would be errors of call or service not found. I think this has to do with the devtools.raw file missing from the etc folder. I had that issue in the past.

There should be a devtools.raw under utils/config that you need to paste into the etc folder of the server so the admin accounts can be used, otherwise you'll get random errors while opening the eve menu and other various issues

**Comment by kimrosebush** [comment]
> There would be errors of call or service not found. I think this has to do with the devtools.raw file missing from the etc folder. I had that issue in the past.
> 
> There should be a devtools.raw under utils/config that you need to paste into the etc folder of the server so the admin accounts can be used, otherwise you'll get random errors while opening the eve menu and other various issues

The file exists in etc/ and utils/config:

```
[root@aa62e5b996c4 config]# ls /app/etc
devtools.raw  eve-server.xml  log.ini
[root@aa62e5b996c4 config]# ls /src/utils/config
MarketBot.xml  README.md  devtools.raw  eve-server.xml  log.ini
[root@aa62e5b996c4 config]# diff /app/etc/devtools.raw /src/utils/config/devtools.raw
[root@aa62e5b996c4 config]#
```

**Comment by kimrosebush** [comment]
Update:
- I rebuilt and am using staging now, the errors are no longer present, maybe related to #246 ??

Thanks!
