### ISSUE TITLE
Once a mission is accepted you cannot open the journal to review it.

### ISSUE THREAD

**Issue by DeerHunt3r** [EvEmu-Project/evemu_Crucible#248]
**Describe the bug**
After accepting a mission you cannot open the journal to review it.

**To Reproduce**
1. accpet a mission - I took one of the delivery missions
2. Click on "journal'
3. Look for the error in the server logs

**Expected behavior**
should open the mission information from the journal

**Screenshots**

**System Details (please complete the following information):**
 - Server OS: [e.g. Ubuntu 20.04 Server]
 - Docker 
 - EVEmu staging branch

**Additional context**
  server_1  | [  9]       0x110e331: EVEServiceManager::Dispatch(std::__cxx11::basic_string<char, std::char_traits<char>, stdc_string<char, std::char_traits<char>, std::allocator<char> > const&, PyCallArgs&) in ./eve-server
server_1  | [  8]        0xc21b11: Client::Handle_CallReq(PyPacket*, PyCallStream&) in ./eve-server
server_1  | [  7]       0x12f1b97: EVEPacketDispatcher::DispatchPacket(PyPacket*) in ./eve-server
server_1  | [  6]        0xc13b3a: Client::ProcessNet() in ./eve-server
server_1  | [  5]        0xc3f94d: EntityList::Process() in ./eve-server
server_1  | [  4]        0xbfd6fb: [unknown function] in ./eve-server
server_1  | [  3]  0x7f81a9c8a510: [unknown function] in /lib64/libc.so.6
server_1  | [  2]  0x7f81a9c8a5c9: [unknown function] in /lib64/libc.so.6
server_1  | [  1]        0xbf9955: [unknown function] in ./eve-server
server_1  | 22:41:16 [Service] invbroker::MachoResolveObject()
server_1  | 22:41:16 [Service] invbroker::MachoBindObject()
server_1  | 22:41:16 [Service] dogmaIM::MachoResolveObject()
server_1  | 22:41:16 [Service] dogmaIM::MachoBindObject()
server_1  | 22:41:16 [Service] aggressionMgr::MachoBindObject()
server_1  | 22:41:16 [Service] config::GetDynamicCelestials()
server_1  | 22:41:16 [Service] beyonce::MachoResolveObject()
server_1  | 22:41:16 [Service] beyonce::MachoBindObject()
server_1  | 22:41:16 [Service] beyonce::GetFormations()
server_1  | 22:41:16 E CheckBallparkTimer(): BallPark Timer is disabled.
server_1  | 22:41:16 [Service] account::GetCashBalance()
server_1  | 22:41:17 [Service] account::GetCashBalance()
server_1  | 22:41:17 [Service] account::GetKeyMap()
server_1  | 22:41:17 [Service] billMgr::GetBillTypes()
server_1  | 22:41:20 [Service] charMgr::GetTopBounties()
server_1  | 22:41:23 [Service] config::GetDynamicCelestials()
server_1  | 22:41:24 [SvcError] EVEServiceManager::ClearBoundObject() - Unable to find bound object 14 to release.
server_1  | 22:41:32 E Client::CallReq: Unable to find method to handle call to: ::GetMissionJournalInfo
server_1  | 22:41:32 E Client::CallReq: GetMissionJournalInfo candidates:
server_1  |     (PyInt*,PyInt*)
server_1  |
server_1  |
server_1  | Does not match parameters:
server_1  |     (PyNone*,PyNone*)
server_1  | 22:41:32 E Network: Failed to marshal new packet.
server_1  | 22:42:45 [DestinyError] Destiny::ProcessState() Error!  Ship Xirong's Noob Ship(140000026) for Player Xirong(90ime > shipTimeToWarp.
server_1  | 22:44:00 [Service] invbroker::MachoResolveObject()
server_1  | 22:44:00 [Service] invbroker::MachoBindObject()
server_1  | 22:44:00 [Service] dogmaIM::MachoResolveObject()
server_1  | 22:44:00 [Service] dogmaIM::MachoBindObject()
server_1  | 22:44:00 [Service] LSC::JoinChannels()
server_1  | 22:44:00 [Service] beyonce::MachoResolveObject()
server_1  | 22:44:00 [Service] LSC::LeaveChannels()
server_1  | 22:44:00 E Client::CallReq: Unable to find method to handle call to: LSC::LeaveChannels
server_1  | 22:44:00 E Client::CallReq: LSC::LeaveChannels candidates:
server_1  |     (PyList*,PyInt*,PyLong*)
server_1  |
server_1  |
server_1  | Does not match parameters:
server_1  |     (PyList*,PyBool*,PyLong*)
server_1  | 22:44:00 E Network: Failed to marshal new packet.
server_1  | 22:44:00 [Service] config::GetDynamicCelestials()
server_1  | 22:44:00 [Service] beyonce::MachoBindObject()
server_1  | 22:44:00 [Service] stationSvc::GetSolarSystem()
server_1  | 22:44:00 [Service] beyonce::GetFormations()
server_1  | 22:44:00 W CheckBallparkTimer(): BallPark Time remaining 1126ms
server_1  | 22:44:00 [Service] sovMgr::GetSystemSovereigntyInfo()
server_1  | 22:44:00 [SovInfo] SovereigntyDataMgr::GetSystemSovereignty(): Faction system 30005304 found, Sending no SovDat
server_1  | 22:44:06 [Service] config::GetDynamicCelestials()
server_1  | 22:44:34 [Service] machoNet::GetTime()
server_1  | 22:44:34 [Service] machoNet::GetTime()
server_1  | 22:44:34 [Service] machoNet::GetTime()
server_1  | 22:44:34 [Service] machoNet::GetTime()
server_1  | 22:44:34 [Service] machoNet::GetTime()
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by Almamu** [comment]
Two methods affected according to the log, easy fix, I'll take a look this afternoon, should be simple fixes...

**Comment by Almamu** [comment]
Fix should be in staging now

**Comment by fishscene** [comment]
Has this been confirmed to be fixed now?

**Comment by d10sfan** [comment]
I'm able to open the journal once I've accepted a mission, so this looks to work now.

**Comment by DeerHunt3r** [comment]
yes it's working.

**Comment by Almamu** [comment]
Okay, I'll be closing this one then, thanks!
