### ISSUE TITLE
Can't Buy from market

### ISSUE THREAD

**Issue by V-Cyberpunk** [EvEmu-Project/evemu_Crucible#252]
**Describe the bug**
It's impossible to buy an item from the market. The item doesn't appear in inventory and the server throws an exception.

**To Reproduce**
1. Go to market
2. Buy an item. In my example, I wanted to buy a skillbook.

**Expected behavior**
Buying the item for ISK and to appear in inventory.

**Screenshots**
<img width="911" alt="Screenshot_20230208_113722" src="https://user-images.githubusercontent.com/44802344/217506659-9b6620c2-3200-41be-83df-b153b23ae89a.png">

**System Details (please complete the following information):**
 - Server OS: Debian 11
 - direct build
 - EVEmu Version 0.8.4-staging-22e8513

**Comment by Almamu** [comment]
Should be fixed on last commit

**Comment by fishscene** [comment]
I can confirm I am able to purchase from the market and it appears in my items.

This can probably be closed.

**Comment by OperationDx** [comment]
I can also confirm this. The exception is if you create a corporation the player is no longer able to purchase anything on the market. But I have is open as a separate issue.

**Comment by V-Cyberpunk** [comment]
never thought, that it is because of my one player corp :D

**Comment by d10sfan** [comment]
This should be fixed, as well as the buying something if you are in a corp, see https://github.com/EvEmu-Project/evemu_Crucible/pull/278
