### ISSUE TITLE
Server crash when put weapons or others onlione

### ISSUE THREAD

**Issue by fumikejin** [EvEmu-Project/evemu_Crucible#257]
**Describe the bug**
I put onlione 125mm Gatling AutoCannon II x3 on ship Heavy Assault Ship-Eagle.
The server crashed when I put the third one online.

I tried it on other ships.
It doesn't matter if I put a turret or other equipment online,server crash when I put the third one online.

**System Details :**
 - Server OS:CentOS7
 - Docker
 - EVEmu Version 0.8.5

**Comment by fumikejin** [comment]
evemu_server  | 11:04:04 [Service] infoGatheringMgr::GetStateAndConfig()
evemu_server  | 11:04:11 [Service] warRegistry::MachoResolveObject()
evemu_server  | 11:04:11 [Service] warRegistry::MachoBindObject()
evemu_server  | 11:04:14 [Service] skillMgr::MachoResolveObject()
evemu_server  | 11:04:14 [Service] skillMgr::MachoBindObject()
evemu_server  | 11:04:15 [Service] certificateMgr::GetAllShipCertificateRecommendations()
evemu_server  | 11:04:15 [Service] certificateMgr::GetCertificateClasses()
evemu_server  | 11:04:15 [Service] insuranceSvc::GetContractForShip()
evemu_server  | 11:04:15 [Service] insuranceSvc::MachoResolveObject()
evemu_server  | 11:04:15 [Service] insuranceSvc::MachoBindObject()
evemu_server  | 11:04:19 [Service] invbroker::MachoBindObject()
evemu_server  | 11:04:26 [Service] dogmaIM::MachoBindObject()
evemu_server  | 11:04:33 [RefPtrError] IncRef() - mDeleted = true.  Count is 26996
evemu_server  | [ 12]       0x143f9f8: debug::CallStack::GetCalls(std::vector<debug::CallStack::CallInfo, std::allocator<debug::CallStack::CallInfo> >&) in ./eve-server
evemu_server  | [ 11]       0x1435dc2: EvE::traceStack() in ./eve-server
evemu_server  | [ 10]        0xc274ce: RefObject::IncRef() const in ./eve-server
evemu_server  | [  9]       0x110c14a: PyResult::operator=(PyResult const&) in ./eve-server
evemu_server  | [  8]        0xc23b9a: Client::Handle_CallReq(PyPacket*, PyCallStream&) in ./eve-server
evemu_server  | [  7]       0x12f2e6b: EVEPacketDispatcher::DispatchPacket(PyPacket*) in ./eve-server
evemu_server  | [  6]        0xc15b5c: Client::ProcessNet() in ./eve-server
evemu_server  | [  5]        0xc41a59: EntityList::Process() in ./eve-server
evemu_server  | [  4]        0xbff6d3: [unknown function] in ./eve-server
evemu_server  | [  3]  0x7f80d4c0b510: [unknown function] in /lib64/libc.so.6
evemu_server  | [  2]  0x7f80d4c0b5c9: [unknown function] in /lib64/libc.so.6
evemu_server  | [  1]        0xbfb955: [unknown function] in ./eve-server
evemu_server  | eve-server: /src/src/eve-core/memory/RefPtr.h:95: void RefObject::IncRef() const: Assertion `mDeleted == false' failed.
evemu_server  | 11:04:33 E     Signal System: Caught signal: 6
evemu_db      | 2023-04-03 11:04:35 13 [Warning] Aborted connection 13 to db: 'evemu' user: 'evemu' host: '192.168.64.3' (Got an error reading communication packets)
evemu_server  | /src/utils/container-scripts/start.sh: line 31:    41 Aborted                 (core dumped) ./eve-server
evemu_server exited with code 134

**This is server's log when server crashed.

**Comment by Almamu** [comment]
Sorry for the big delay, should be fixed on commit 7f6b9b660d00a8c9eea742323fb8fa50965a6125 on staging

**Comment by fumikejin** [comment]
Thanks for the reply.
Yes, bug has been fixed.

**Comment by rrfarmer** [comment]
Can confirm, this bug and is fixed on staging.
