### ISSUE TITLE
After destroying an enemy NPC they can show up on dscan and system scan in the another star system

### ISSUE THREAD

**Issue by OperationDx** [EvEmu-Project/evemu_Crucible#270]
**Describe the bug**
Bug - After destroying an enemy NPC they can show up on dscan and system scan in the another star system.

**To Reproduce**
Purchase and fit a ship.
Warp to a belt and wait for enemy NPC's. 
Destroy enemy NPC.
Jump to another system through a gate.
Open Scanner and run a dscan or a system scan and you will see wrecks

**Expected behavior**
After destroying an enemy NPC in a system and jumping to a new system destroyed NPC's should not show up on player scanner.

**Screenshots**
Maybe will add later

**System Details (please complete the following information):**
 - Server OS: Ubuntu
 - Docker – Latest Staging Build 0.8.5 as of 08/07/2023
 

**Additional context**
None at this time

**Comment by jdhirst** [comment]
Related to #269, closing this in favour of that ticket.
