### ISSUE TITLE
In the character sheet menu clicking on security status causes the character sheet to bug

### ISSUE THREAD

**Issue by OperationDx** [EvEmu-Project/evemu_Crucible#271]
**Describe the bug**
Bug - In the character sheet menu clicking on security status causes the character sheet to bug out no longer letting you click on other tabs.

**To Reproduce**
Open character sheet
Click on security status
Clicking on any other tab in the character sheet will be blank until you log.

**Expected behavior**
Tab should show security status (may not be implemented) clicking on other tabs after should continue to show character information   

**Screenshots**
![C_Sheet](https://github.com/EvEmu-Project/evemu_Crucible/assets/141080303/2bf8911b-1eb1-4272-95d9-c8e2c172c33b)

**System Details (please complete the following information):**
 - Server OS: Ubuntu
 - Docker – Latest Staging Build 0.8.5 as of 08/07/2023
 

**Additional context**
None at this time

**Comment by ZyenDomani** [comment]
this was working.
will need a bit of tracing to find problem.

**Comment by OperationDx** [comment]
Another interesting effect of this is the the market loads way faster ever if the player can't purchase anything.

**Comment by OperationDx** [comment]
Thanks for the update

**Comment by d10sfan** [comment]
Server comes up with this error when trying to open the standings page on your character:

```
01:00:26 E Client::CallReq: Unable to find method to handle call to: standing2::GetStandingTransactions

01:00:26 E Client::CallReq: standing2::GetStandingTransactions candidates: 

	(PyInt*,PyInt*,PyInt*,PyInt*,PyInt*,PyLong*)

Does not match parameters: 

	(PyInt*,PyInt*,PyInt*,PyNone*,PyNone*,PyNone*)

```

I have a fix that should work for this in a PR, now the standing screen loads and seems to work from what I can tell.

![image](https://github.com/EvEmu-Project/evemu_Crucible/assets/4337981/8e3e0b74-63d6-4304-81a4-a860e53a8a42)

**Comment by d10sfan** [comment]
If you try the latest from staging, my changes have been merged, so this should be fixed.

**Comment by OperationDx** [comment]
Thank you.

**Comment by jdhirst** [comment]
Closing as fixed
