### ISSUE TITLE
Contract

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#28]
From AlasiyaEvE created by [h4h4h4](https://github.com/h4h4h4): zhyrohaad/AlasiyaEvE#132  

**Describe the bug**
When creating a contract , i am stuck on "retrieving item list.,..." 

**To Reproduce**
try to create a contract (public)

**Expected behavior**
should listed items in personal hangar

**Screenshots**

**Additional context**

**Comment by jdhirst** [comment]
this system is mostly skeleton code, with a few calls that return something.
it is on the list, but quite low.
its current status is listed in code status page  http://eve.alasiya.net/?p=op_status

**Comment by VizanArkonin** [comment]
Oh, didn't know we had the ticket so early, lol
I'm keeping track of it in #165

**Comment by zhyrohaad** [comment]
this was pulled over from my branch.
we'll delete it in favor of yours.  :)
