### ISSUE TITLE
Client Login prompt The password you entered is incorrect.

### ISSUE THREAD

**Issue by code-subscription** [EvEmu-Project/evemu_Crucible#284]
I crate account use :INSERT INTO account (accountID, accountName, role, password, online, banned) VALUES(NULL, 'admin', 5003499186008621056, 'admin', 0, 0);
then the client login prompt:password incorect
how to create a account to login ? help

**Comment by ZyenDomani** [comment]
the passwords in the database are supposed to be encrypted.    plain passwords are not supported (or they werent)
i dont know if it was removed, but you should be able to create an account just by logging into the game. (autoaccount)

**Comment by oowow-core** [comment]
1st login, it will create username password
2nd login, use password in #1

**Comment by jdhirst** [comment]
Closing as solved.
