### ISSUE TITLE
Changing the name of a control tower does not update correctly

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#55]
From AlasiyaEvE created by [ryllae](https://github.com/ryllae): zhyrohaad/AlasiyaEvE#72  

Right click on an anchored and online control tower, choose "Change Name".  Nothing updates on your screen.  Warp out and back, your change has taken effect.

I had a second control tower that was anchored prior to the fixes, but never onlined - I can change its name correctly, even while unachoring.

Will test further, but setting up a new POS takes a while...

**Comment by jdhirst** [comment]
i had 2 in same system i test with.
they both do this....havent cared enough to even look into it at this point.
it does show right in all menus, and even on the scanner.

p.s.  system scanner will show pos and other things...just fyi

**Comment by jdhirst** [comment]
Can't deploy any towers.  Existing towers are either broken or invisible.  See comment in https://github.com/zhyrohaad/AlasiyaEvE/issues/68

**Comment by jdhirst** [comment]
found, fixed
main updated

**Comment by jdhirst** [comment]
any updates on this?

**Comment by zhyrohaad** [comment]
i have verified this again.
closing issue.
