### ISSUE TITLE
Market Transaction window shows that you're always self-dealing

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#80]
From AlasiyaEvE created by [ryllae](https://github.com/ryllae): zhyrohaad/AlasiyaEvE#105  

Sell an item on the market.  Open the Wallet -> My Wallet -> Transactions -> Sell.  All your sell orders have your own name as the buyer.

Likewise, all Buy orders have your own name instead of the seller.

**Comment by jdhirst** [comment]
It's also DOG SLOW.  took me several minutes just to buy and sell a couple items back and forth.

**Comment by jdhirst** [comment]
market code has been rewritten and vastly improved.
the slow part im not sure about.....its hard to test latency on internal network.  :/

**Comment by jdhirst** [comment]
the slow part i'll look into as i get time.

**Comment by jdhirst** [comment]
this is expected.
market is only marginally complete, and hasnt been messed with once the 'basics' were working.
at this point, buying and selling mostly works, so it's not very high on the list.

**Comment by charles-m-knox** [comment]
I fixed this in https://github.com/EvEmu-Project/evemu_Crucible/pull/291 (currently merged in the `staging` branch). (No intentional changes to any latency were made on my part though).
