### ISSUE TITLE
Launching POS causes Seg Fault

### ISSUE THREAD

**Issue by grenval** [EvEmu-Project/evemu_Crucible#82]
**Describe the bug**
Unable to launch a POS, doing so causes a Seg fault.

**To Reproduce**
1. Go to Any moon, in my case it was in nullsec
2. Click on Launch/Deploy button on the POS in your ship inventory

**Expected behavior**
To see the POS appear in the direction of the moon, in an unanchored state.

**System Details (please complete the following information):**
 - Server OS: Ubuntu 20.04 Server
 - Direct build
 - EVEmu Version 0.8.3

**Comment by zhyrohaad** [comment]
`m_destiny->SetPosition(pos);`
possible `m_destiny` is not set properly for tower.

> #2  0x0000555556099617 in DestinyManager::SetPosition (this=0x0, pt=...,
    update=false)
    at /home/simon/games/evemu_Crucible/src/eve-server/system/DestinyManager.cpp:2317
No locals.
#3  0x0000555555f8baae in StructureSE::SetAnchor (this=0x55555e798200,
    pClient=0x5555574b5370, pos=...)
    at /home/simon/games/evemu_Crucible/src/eve-server/pos/Structure.cpp:514
        dist = 100000
        radius = 910000
        rad = 1.57079637
        updates = std::vector of length 12500, capacity 0 = {
          <error reading variable updates (Cannot access memory at address 0x0)>

**Comment by zhyrohaad** [comment]
update.
this is a core error.
will need to be updated in tower code.
in this case, we are adding a Destiny object to an OSE, so c'tor/d'tor will have to be put into TowerSE class.
`m_destiny = new Destiny()`  <<< INCOMPLETE...needs more data here
^^^ that needs to be put in `void TowerSE::Init()` in pos/Tower.cpp:145
if anyone wants to try this, then go for it.
if not, i'll fix when i get time.

**Comment by grenval** [comment]
Note: The POS appears after the server is re-launched.

**Comment by jdhirst** [comment]
@grenval this has been confirmed fixed in `staging`. This will be released as part of 0.8.4.
