### ISSUE TITLE
Implement Alliances

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#89]
Stub feature req for Alliances. To be used as part of project for tracking.

**Comment by jdhirst** [comment]
# Things to fix #
- [ ] Alliance logo does not persist reloading of client for some reason (maybe just on Linux, not sure)

# Things to implement #
- [ ] Alliance maintenance bill
- [ ] Alliance contacts

**Comment by mkjeller** [comment]
EVEmu Server v0.8.3 (04 April 2021) [Staging Branch]

Attempted to form alliance, failed due to lack of funds.
Used `.giveisk` to give myself 1B ISK to form the alliance.
Successfully formed alliance, 1B ISK remained in wallet.

**Comment by jdhirst** [comment]
With this last fix, I'm pretty happy with the current state of Alliances. I'm sure there are still things missing, but this should be enough to continue with Sovereignty.

Moving to testing in project.

**Comment by jdhirst** [comment]
Closing this off as everything seems to be working. If there is anything missing, please open a new issue and I'll have a look.
