### ISSUE TITLE
Wallet transactions show 0 quantity and 0 credit

### ISSUE THREAD

**Issue by ekg98** [EvEmu-Project/evemu_Crucible#96]
**Describe the bug**
Wallet transactions show 0 quantity and 0 credit after selling items.

**To Reproduce**
1. Sell item
2. View transactions in wallet

**Expected behavior**
quantity should show quantity sold and amount credited

**System Details (please complete the following information):**
 - Server OS: Windows 10
 - Docker
 - EVEmu Version 0.8.3

**Comment by zhyrohaad** [comment]
player selling (via personal or corp) is incomplete.
market rewrite is still in 'testing' phase.

**Comment by charles-m-knox** [comment]
I fixed this in https://github.com/EvEmu-Project/evemu_Crucible/pull/291 (currently merged in the `staging` branch).

**Comment by jdhirst** [comment]
Closing as fixed
