### ISSUE TITLE
seed_station_market.sql does not seed station

### ISSUE THREAD

**Issue by ekg98** [EvEmu-Project/evemu_Crucible#99]
**Describe the bug**
seed_station_market.sql does not seed the desired station.  Difference between SELECT statement in seed_station_market.sql and seed_market.sql is different.  

seed_station_market.sql uses stationID for ownerID.  This sql doesn't work.
seed_market.sql uses corporationID for ownerID.  This sql works.

Not sure if this is what is causing it.  Just tried to do a bit of investigation.

**To Reproduce**
1. Add sql to DB with mysql or HeidiSQL
2. View Market

**Expected behavior**
Should seed station market with orders

**System Details (please complete the following information):**
 - Server OS: Windows 10
 - Docker
 - EVEmu Version 0.8.3

**Comment by zhyrohaad** [comment]
seed_station works for me, as this is what i use.
can you detail how you're running it and any sql errors.

the ownerID is negligible.  it doesnt matter what's in there, as long as the value is an actual owner. (corp, faction, station, npc, pc)

**Comment by ekg98** [comment]
This has fixed the issue.  Thanks
